updates for RRFS baseline E
NOAA-GSL/fv3atm pull request #157
Opened 2022-10-10 16:36 UTC by hu5970

This update is to bring two changes for baseline E:

1) Add changes from Jun Wang for fast read restart files (Those changes are in community repository)
2) Add changes from Tanya and links to the submodule.

This PR depends on the following two PRs:
https://github.com/NOAA-GSL/ccpp-physics/pull/164
https://github.com/NOAA-GSL/GFDL_atmos_cubed_sphere/pull/13

2022-10-11 14:23 UTC, joeolson42 approved these changes

2022-10-11 14:24 UTC, hannahcbarnes approved these changes

2022-10-11 14:41 UTC, haiqinli approved these changes

2022-10-11 15:52 UTC, SamuelTrahanNOAA requested changes
Smoke debug tests fail with a floating-point exception at line 5353 of module_bl_mynn.F90.

2022-10-11 16:01 UTC, mdtoyNOAA approved these changes

2022-10-11 16:27 UTC, tanyasmirnova approved these changes

2022-10-11 17:07 UTC, zhanglikate approved these changes

2022-10-12 21:46 UTC, tanyasmirnova approved these changes

2022-10-13 15:05 UTC, SamuelTrahanNOAA approved these changes

2022-10-13 15:06 UTC, merged