1. Move initialization of stochastic physics after the physics
NOAA-GSL/fv3atm pull request #65
Opened 2020-12-21 17:38 UTC by tanyasmirnova

1. Move initialization of stochastic physics after the physics in CCPP in atmos_model.F90.
2. Added albedo variables to land perturbations with lndp_type=2 option in stochastic_physics_wrapper.F90
Also, changes to accommodate soil perturbations with RUC LSM.
Associated PR is NOAA-GSL/stochastic_physics - PR#1.

## Description

(Instructions: this, and all subsequent sections of text should be removed and filled in as appropriate.)
Provide a detailed description of what this PR does.  
What bug does it fix, or what feature does it add?  
Is a change of answers expected from this PR?  

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes #<issue_number>
- fixes noaa-emc/fv3atm/issues/<issue_number>

## Testing

How were these changes tested?  
What compilers / HPCs was it tested with?  
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
Have the ufs-weather-model regression test been run? On what platform?  
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
- Please commit the regression test log files in your ufs-weather-model branch

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

2020-12-28 23:53 UTC, DomHeinzeller requested changes
The variables pores and resid are not defined:
```
/Users/dom.heinzeller/scratch/ufs-weather-model/ufs-weather-model-gsl-develop-20201228-land-stochastic-perturbations/gnu/FV3/stochastic_physics/stochastic_physics_wrapper.F90:229:76:

  229 |                                sfc_wts, xlon, xlat, stype, GFS_Control%pores, GFS_Control%resid,                &
      |                                                                            1
Error: 'pores' at (1) is not a member of the 'gfs_control_type' structure
```
See:
```
heinzeller-lt:ufs-weather-model-gsl-develop-20201228-land-stochastic-perturbations dom.heinzeller$ grep -RiE 'pores|resid' FV3/gfsphysics/GFS_layer/
FV3/gfsphysics/GFS_layer//GFS_typedefs.F90:    ! Beware! The values set here reside in wam_f107_kp_mod and determine sizes of arrays
```

2020-12-28 23:53 UTC, DomHeinzeller commented on stochastic_physics/stochastic_physics_wrapper.F90
> +        if (GFS_Control%lsm == 1) then
`== GFS_Control%lsm_noah`

2020-12-28 23:53 UTC, DomHeinzeller commented on stochastic_physics/stochastic_physics_wrapper.F90
> +               if (GFS_Control%lsm == 1) then
`== GFS_Control%lsm_noah`

2020-12-28 23:53 UTC, DomHeinzeller commented on stochastic_physics/stochastic_physics_wrapper.F90
> +             if (GFS_Control%lsm == 1) then
`== GFS_Control%lsm_noah`

2020-12-28 23:53 UTC, DomHeinzeller commented on stochastic_physics/stochastic_physics_wrapper.F90
> +                               sfc_wts, xlon, xlat, stype, GFS_Control%pores, GFS_Control%resid,                &
in stochastic_physics, I see in the argument list for ldnp_apply_perts`:
```
...
stype, maxsmcnoah, maxsmc,        &
param_update_flag,           &
...
```
is `GFS_Control%pores` indeed  `maxsmcnoah`, and `GFS_Control%resid` indeed `maxsmc`?

2020-12-28 23:53 UTC, DomHeinzeller commented on stochastic_physics/stochastic_physics_wrapper.F90
> +                               sfc_wts, xlon, xlat, stype, GFS_Control%pores, GFS_Control%resid,                &
Update after commits a44daed3dd16031af01067200109d8eb73207034 and 57afa4d42b5cb9c2225b83def22f54bbcb9eba4d were made to the stochastic_physics PR. `GFS_Control%pores` now corresponds to `smcmax`, and `GFS_Control%resid` to `smcmin`.

2020-12-29 00:00 UTC, tanyasmirnova commented
@DomHeinzeller I just have pushed the changes to GFS_typedefs.F90 to add pores and resid variables.

2020-12-29 00:04 UTC, climbfuji commented
> @DomHeinzeller I just have pushed the changes to GFS_typedefs.F90 to add pores and resid variables. The changes are in my gsl_landstoch_withruc branch.

Thank you! How do these arrays get initialized? They are set to `clear_val`, but I assume they should be set in the call to `set_soilveg` (currently still outside CCPP) or `set_soilveg_ruc` (inside CCPP)? Is this something you need help with?

2020-12-29 00:08 UTC, tanyasmirnova commented
@climbfuji Dom, yes, they are initialized in set_soilveg (with the Noah or Noah_MP) and set_soilveg_ruc with RUC LSM. I tested with both Noah and RUC LSMs - worked fine with both.

2020-12-29 00:13 UTC, climbfuji commented
> @climbfuji Dom, yes, they are initialized in set_soilveg (with the Noah or Noah_MP) and set_soilveg_ruc with RUC LSM. I tested with both Noah and RUC LSMs - worked fine with both.

That's good news, but unfortunately I do not see the code changes - is this all in a yet-to-come ccpp-physics PR? Or half in the fv3atm PR, and half in ccpp-physics?

2020-12-29 00:37 UTC, tanyasmirnova commented
@climbfuji Dom, I am still confused with this PR. Could you please check my gsl_landstoch_withruc branches in fv3atm and ccpp-phys? Should I make separate PRs in there?

2020-12-29 00:47 UTC, tanyasmirnova commented
I have made a PR in ccpp-phys

2020-12-29 02:56 UTC, DomHeinzeller commented
> I have made a PR in ccpp-phys

Thanks, Tanya. I briefly looked at the ccpp-physics PR, and it's looking good. Will test tomorrow!

2020-12-29 21:14 UTC, DomHeinzeller commented
This PR is now part of #68 and will be merged automatically as part of it. Do not merge separately.

2020-12-30 15:37 UTC, DomHeinzeller commented on stochastic_physics/stochastic_physics_wrapper.F90
> +        if (GFS_Control%lsm == 1) then
Fixed in https://github.com/NOAA-GSL/fv3atm/pull/68

2020-12-30 15:38 UTC, DomHeinzeller commented on stochastic_physics/stochastic_physics_wrapper.F90
> +             if (GFS_Control%lsm == 1) then
Fixed in https://github.com/NOAA-GSL/fv3atm/pull/68

2020-12-30 15:38 UTC, DomHeinzeller commented on stochastic_physics/stochastic_physics_wrapper.F90
> +                               sfc_wts, xlon, xlat, stype, GFS_Control%pores, GFS_Control%resid,                &
Now fixed.

2021-01-08 18:28 UTC, DomHeinzeller approved these changes

2021-01-09 02:52 UTC, DomHeinzeller commented
This PR was merged as part of https://github.com/NOAA-GSL/fv3atm/pull/68.

2021-01-09 02:52 UTC, closed without merging