Add dependency of ccpp-physics on gocart library to CMakeLists.txt
NOAA-GSL/fv3atm pull request #84
Opened 2021-04-20 14:30 UTC by climbfuji

## Description

This PR addsa dependency of ccpp-physics on the gocart library to `CMakeLists.txt`

## Testing

See MISSING

## Dependencies

https://github.com/NOAA-GSL/ccpp-physics/pull/87
MISSING

2021-04-22 21:52 UTC, zhanglikate approved these changes

2021-04-22 22:03 UTC, haiqinli approved these changes

2021-04-23 11:16 UTC, SamuelTrahanNOAA requested changes
If a new plumerise module is needed, it should be copied into gsd-chem, or all of gsd-chem's non-wrapper modules should be in GOCART. This half-way solution makes the code worse, not better. As an interim solution, the modules should be copied into gsd-chem, and we should make an end goal of either keeping everything there, or moving it to GOCART.

2021-04-23 12:29 UTC, merged

2021-04-23 12:56 UTC, DomHeinzeller commented
This should not have been merged before ccpp-physics, not sure how this happened.